### ISSUE TITLE
Curly braces inside function prototype gets broken into new lines by tidy_source()

### ISSUE THREAD

**Issue by rsaporta** [yihui/formatR#43]
Not sure if this is intended behavior or not.  Would it be possible for the user to control this behavior (ie turn it off if undesired)? 

    exampleFunc <- function(x, y={if (x > 5) -1 else NA}, z=0) {
      print ("hello World")
    }

       vvvvv tidy_source() vvvvvvvv

    exampleFunc <- function(x, y = {
        if (x > 5)
            -1 else NA
    }, z = 0) {
        print("hello World")
    }

**Comment by yihui** [comment]
Sorry, but I do not think there is a way to turn it off. In this particular case, I do not see why the curly braces are necessary, i.e.

```r
exampleFunc <- function(x, y=if (x > 5) -1 else NA, z=0) {
  print ("hello World")
}
```
