### ISSUE TITLE
Spaces around + but not around / and ^?

### ISSUE THREAD

**Issue by schuemie** [yihui/formatR#45]
This doesn't seem to follow the style guide:
```r
tidy_source(text="x <- a + 2")
# x <- a + 2 
tidy_source(text="x <- a / 2")
# x <- a/2 
tidy_source(text="x <- a ^ 2")
# x <- a^2 
```

**Comment by yihui** [comment]
I asked the same question a couple of years ago: http://comments.gmane.org/gmane.comp.lang.r.devel/27423 I'm afraid there is not much that I can do, since this has been baked deep in base R. Sorry.
