### ISSUE TITLE
Comments after arguments in functions

### ISSUE THREAD

**Issue by asdftyp** [yihui/formatR#47]
Running following code on tidy_app()

    foo <- function(ParamA = 1, # comment 
    		ParamB="c"){ 
      print("hi") 
    }

Produces 

    Error in base::parse(text = code, srcfile = NULL) : 
      1:26: unexpected SPECIAL
    1: foo <- function ( ParamA %InLiNe_IdEnTiFiEr%

Environment:
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)

shiny_0.12.1
formatR_1.2

**Comment by yihui** [comment]
That is by design: http://yihui.name/formatR
