### ISSUE TITLE
Compile notebook chunks

### ISSUE THREAD

**Issue by caleblareau** [yihui/formatR#52]
In the comment chunks that RStudio interprets when compiling a notebook, running the reformat code makes the chunk options not function correctly.

e.g.
#+ fig.width=16, fig.height=5, message = FALSE, warning = FALSE, echo=FALSE

goes to
 # + fig.width=16, fig.height=5, message = FALSE, warning = FALSE,
 # echo=FALSE

**Comment by yihui** [comment]
Fixed. Thanks!
