### ISSUE TITLE
Multiple assignment gets reformatted incorrectly

### ISSUE THREAD

**Issue by bpbond** [yihui/formatR#59]
We have an issue (see https://github.com/PecanProject/pecan/issues/1130) where formatR changed
```R
s1 <- s2 = 0.1
```

to

```R
(s1 <- s2) <- 0.1
```

...which is obviously syntactically different. This occurred with formatR 1.4, run with arrow=TRUE.

Thanks to @SimonGoring for spotting this.

**Comment by yihui** [comment]
That is not surprising to me, because `<-` has higher precedence than `=`. `s1 <- s2` has to be executed before the next assignment. See `?Syntax`.

In general, it is a bad idea to mix `<-` with `=`. It is find to use either, but just not both.

**Comment by bpbond** [comment]
> it is a bad idea

Um, yes, exactly. That's why we were running formatR on the code, to clean up that kind of thing. Well, thanks anyway.
