### ISSUE TITLE
Blank lines not removed

### ISSUE THREAD

**Issue by chochkov** [yihui/formatR#64]
I have a file called `test.R` like so:

```R

if (TRUE)

{

       a = 12
}


print(a)
```

Then I run the following cmmand on it:

```
R --no-readline --vanilla -q --slave -e 'formatR::tidy_source("test.R", indent=2, arrow=TRUE)'
```

and receive output:

```R

if (TRUE)
{

  a <- 12
}


print(a)
```

and not the expected:

```R
if (TRUE) {
  a <- 12
}

print(a)
```

**Comment by yihui** [comment]
If you want to remove blank lines, you have to use `blank=FALSE`. The default is to preserve blank lines.

**Comment by chochkov** [comment]
@yihui I see now (I got confused how to read the the `blank` parameter)

However, you see how the blank line between the `if` and the `{` got removed? This I find expected as default behaviour. But I'd also expect the blank line following the `{` and before the first expression to be removed, which right now it doesn't.

Also the `blank=TRUE` deletes *all* blank lines, which IMHO isn't the expected behaviour; Instead multiple blank lines should be coerced into a single blank line (similarly to how it works for whitespace). 

I'd be happy to contribute code for any of these - imho at least - issues if you find that might be useful.

**Comment by chochkov** [comment]
So to summarise, I see that removing the blank between an `if` and a `{` is documented here https://yihui.name/formatr/ to work whatever the `blank` parameter is and that's great. So what I'm suggesting is two things: 

- [ ] we replace coalesce repeated blank lines into one (by e.g. extending the values of the `blank` parameter into a range, say, `c('all', 'repeated', 'none')` according to the current behaviour `none` would be default;
- [ ] strip blank lines between a block opening `{` and first expression and/or between a last expression and a block closing `}`

**Comment by yihui** [comment]
Sorry I'm not really interested in that level of granularity, and the implementation does not sound trivial to me. Thanks for the suggestions, though.
