### ISSUE TITLE
space around binary operators

### ISSUE THREAD

**Issue by sje30** [yihui/formatR#69]
Is it by accident that space is added around some, but not all, binary operators?

```
> tidy_source(text="a<-3+4")
a <- 3 + 4
> tidy_source(text="a=3+4")
a = 3 + 4
> tidy_source(text="a=3/4")
a = 3/4
> tidy_source(text="a=3*4")
a = 3 * 4
> tidy_source(text="a=3-4")
a = 3 - 4
> tidy_source(text="a=3%/%4")
a = 3%/%4
> tidy_source(text="a=3%%4")
a = 3%%4
```

great package by the way!

**Comment by yihui** [comment]
I believe someone in R core thought division operators were special compared to other operators. 

```r
> deparse(parse(text = '3+4')[[1]])
[1] "3 + 4"
> deparse(parse(text = '3*4')[[1]])
[1] "3 * 4"
> deparse(parse(text = '3/4')[[1]])
[1] "3/4"
> deparse(parse(text = '3%%4')[[1]])
[1] "3%%4"
```

You may see more info at https://yihui.name/formatr/#7-how-does-tidy-source-actually-work

**Comment by sje30** [comment]
Thanks! 

In the meantime I found styler package - which does handle the operators consistently.  Is that likely to be the successor to your package, or will they have different aims?

**Comment by yihui** [comment]
I'll see how well it goes after the GSoC this year. It has the potential to replace formatR.
