### ISSUE TITLE
parsing error when there's an inline comment 

### ISSUE THREAD

**Issue by aminadibi** [yihui/formatR#70]
Seems `tidy_source `is unable to parse inline comments. 
Here's an example in clipboard:
```
input$test<-cbind(
    m=c(intercept= 1-0.1,age=-0.2),# Updated 
    f=c(intercept=2-0.4,age=-0.5)) # Updated 
```

formatR error output:
```
> tidy_source(indent = 2)
Error in base::parse(text = code, keep.source = FALSE) : 
  <text>:2:47: unexpected SPECIAL
1: input $ test <- cbind (
2: m = c ( intercept = 1 - 0.1 , age = - 0.2 ) , %InLiNe_IdEnTiFiEr%
```

Would be nice to handle those.

Cheers!

**Comment by yihui** [comment]
Please read Section 6 in the documentation: https://yihui.name/formatr/

**Comment by aminadibi** [comment]
Yeah I have read the doc. Is it not supposed to move the comment, as opposed to giving an error?

**Comment by yihui** [comment]
It is hard to deal with this case. If you know how, I'll truly appreciate your pull request!
