### ISSUE TITLE
New feature request: do not merge comment lines

### ISSUE THREAD

**Issue by YongLiedu** [yihui/formatR#73]
Sometimes it would be better to ignore/don't merge comment lines.

avoid change something like this

\# this is a sample.
\# **_bash command and parameters here_**
\# results

to

\# this is a sample. **_bash command_**
\# **_and parameters here_** results

**Comment by yihui** [comment]
Sounds like a reasonable feature request, but I don't have time to implement it. All I can say right now is that pull requests are welcome!

Also note roxygen comments `#'` will never be rewrapped.

**Comment by yihui** [comment]
Implemented via 4e31ffb. Thanks!
