### ISSUE TITLE
tidy_dir reformats NA_real_ to _real_

### ISSUE THREAD

**Issue by phaverty** [yihui/formatR#74]

**Comment by yihui** [comment]
I cannot reproduce it.

```r
> formatR::tidy_source(text='x = NA_real_')
x = NA_real_
```

Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)? Please also include your session info:

```r
devtools::session_info('formatR')
```
