### ISSUE TITLE
 Comments inline with function args not parsing in formatR::tidy_file

### ISSUE THREAD

**Issue by BarryDowrick** [yihui/formatR#81]
Hi Yihui
I love the package!
I have been using it to improve some scripts which have grown a bit messy and in so doing I have found that there are some situations where valid code is not parsed:

**I get the following:**

> formatR::tidy_file('./R/test_formatR.R')
tidying ./R/test_formatR.R
Error in base::parse(text = code, keep.source = FALSE) : 
  <text>:17:18: unexpected SPECIAL
16: options = list ( autoWidth = FALSE ,
17: dom = "Bfrtip" , %InLiNe_IdEnTiFiEr%
                     ^
>
**Here is the './R/test_formatR.R' script:**
`# Sample

#' Produces a copy read table in the viewer pane of RStudio
#'
#' @param dt A dataframe to copy from viewer
#' @param .cap A character string for the title
#' @return A datatable in the form of a javascript object that can be Viewed in RStudio or added to html via shiny or RMD
#'
#' @export
cr_clip <- function(dt, .cap = "title") {
    DT::datatable(
      data = dT,
      caption = .cap,
      extensions = c("Buttons"),
      filter = "top",
      options = list(autoWidth = FALSE,
                     dom = "Bfrtip", # explanation......
                     bPaginate = FALSE,
                     searchHighlight = FALSE,
                     buttons = c("copy"),
                     scrollX = TRUE,
                     autoFill = TRUE))
}`

removing *# explanation* allows tidy_file() to parse this file and repair formatting.  This is an easy enough workaround but I would prefer to be able to add explanatory comment inline with function arguments.

All the best and thanks for all the work.
Barry

**Comment by yihui** [comment]
This is a known case that formatR cannot deal with and it is documented at: https://yihui.name/formatr/#6-further-notes
